### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome#9]
PHPUnit with the DBUnit add-on would be suitable testing frameworks.

Fat Free also has a testing framework which could be good for testing routes: https://fatfreeframework.com/unit-testing

**Comment by jmauerhan** [comment]
Do you also need help writing some tests? I see you added the PHP Unit tool, but don't yet have any tests that I can see. I'd be happy to help out with this - just let me know!

**Comment by dbudwin** [comment]
I would love some help!  I'm hesitant to add more functionality until I have some tests in place. I spent some time this afternoon trying to write some tests but my inexperience with PHP and PHPUnit was prohibitive.  I got Travis CI set up to hopefully entice someone to help me with testing.

**Comment by jmauerhan** [comment]
Cool - is `MQTTPublisher.php` the only source code you have so far, or did I just miss the codebase?

**Comment by dbudwin** [comment]
The part of the code that could use testing are my models and controllers in this folder. https://github.com/dbudwin/RoboHome/tree/master/web/fatfree/app

I imagine a good way to test my models is to pass in data and make sure a mocked DB gets modified as expected. I read PHPUnit handles this well. For the controller classes I think a good test is that it rerouted the user to the correct page.  I'm not sure if you have any experience with Fat Free PHP or MVC so let me know if you have any questions. You probably know a lot more PHP than I do so I'll be grateful for any help. Even just improvements to my code as is.

**Comment by fgs-dbudwin** [comment]
Hey @jmauerhan, I was wondering if this was still something you're willing to help me with or if you had any questions.

**Comment by dbudwin** [comment]
Hey @jmauerhan, I was wondering if this was still something you're willing to help me with or if you had any questions.

**Comment by jmauerhan** [comment]
I am definitely happy to help out - it's on my list :)

**Comment by dbudwin** [comment]
Awesome!  I just created issues #17 and #18 to add a little more granularity and clarity around unit testing this project since this issue is technically resolved and I plan on closing it now.  I'm open to any ideas you may have for testing as well if those issues don't align with what you may have envisioned.
